# Generated by Django 2.2 on 2020-02-24 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelbud_app', '0002_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='addedby',
            new_name='user',
        ),
    ]
