# Generated by Django 2.2 on 2020-02-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbud_app', '0003_auto_20200224_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='joiners',
            field=models.ManyToManyField(related_name='trip_joiners', to='travelbud_app.User'),
        ),
    ]
